### ISSUE TITLE
最新版还是下载不了歌曲

### ISSUE THREAD

**Issue by phpyii** [messoer/Music-Downloader_TJS#2]
最新版还是下载不了歌曲

**Comment by 17665347409** [comment]
我在学校所以没有办法恢复
问题应该是这样的，服务器中间层又更新了，我还没有部署最新的中间层到服务器上

**Comment by 17665347409** [comment]
> 最新版还是下载不了歌曲

更新
现在由于API已经停止更新，我在尝试自己恢复一部分下载的使用

**Comment by 17665347409** [comment]
> > 最新版还是下载不了歌曲
> 
> 更新
> 现在由于API已经停止更新，我在尝试自己恢复一部分下载的使用

更新
现在已经恢复QQ音乐的专辑图片和MV下载功能

**Comment by 17665347409** [comment]
> > > 最新版还是下载不了歌曲
> > 
> > 
> > 更新
> > 现在由于API已经停止更新，我在尝试自己恢复一部分下载的使用
> 
> 更新
> 现在已经恢复QQ音乐的专辑图片和MV下载功能

更新
目前QQ音乐和网易云音乐标准品质歌曲下载都已经恢复完成可以正常使用
